### PR TITLE
Remove ItoLife raw codes

### PR DESCRIPTION
**Pull request by mmyoji**
* created [ruboty-ito_life](https://github.com/mmyoji/ruboty-ito_life) gem and remove all codes from this repo
* u don't need to have `handler.rb` any longer.
    * if you want to `.env` file, just run `bundle exec ruboty --dotenv`

### CODE REVIEW

**Comment by mmyoji** [comment]
is this repo still active?

**Comment by nownabe** [comment]
It's time to revival! 😈

**Comment by nownabe** [comment]
LGTM! thx!

**Comment by mmyoji** [comment]
寿司ゆき:thanks

**Pull request merged**
